version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: document_pipeline
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGHOST: db
      PGDATABASE: document_pipeline
      PGPORT: 5432

  worker:
    build: ./worker
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: mysecretpassword
      PGHOST: db
      PGDATABASE: document_pipeline
      PGPORT: 5432

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db_data:
